# -*- coding: utf-8 -*-
"""Time Table Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1deRTKvXBKSM5BtHXSxULwgu8gPE5bGhQ
"""

import pandas as pd
import random

print("TIMETABLE GENERATOR \n")

#User inputs
subjects_input = input("enter subjects(comma seperated): ")
days_input = input("enter days(comma separated): ")
periods_per_day = int(input("enter number of periods per day:"))

#Process Inputs
subjects = [s.strip() for s in subjects_input.split(",") if s.strip()]
days = [d.strip() for d in days_input.split(",") if d.strip()]

#validation
if len(subjects) == 0 or len(days) == 0 or periods_per_day <= 0:
  print("Invalid input.Please try again.")
else:
  timetable = {}

  for day in days:
    timetable[day] = random.choices(subjects, k=periods_per_day)



#Create DataFrame
df = pd.DataFrame(timetable)
df.index = [f"Period {i+1}" for i in range(periods_per_day)]

print("\n Timetable Generated Successfully \n")
display(df)

#Save Timetable
df.to_csv("timetable.csv")
print("\n Timetable saved as timetable.csv")